FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o bin/ai-service cmd/ai-service/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bin/ai-service .
RUN apk add --no-cache ca-certificates
CMD ["./ai-service"]