FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o bin/resume-service cmd/resume-service/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/bin/resume-service .
COPY .env .
CMD ["./resume-service"]